In [3]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [5]:
# create tensors 
x = torch.tensor(1.0,requires_grad=True)
w = torch.tensor(2.0,requires_grad=True)
b = torch.tensor(3.0,requires_grad=True)

In [6]:
# Build a computational graph
y = x*w + b


In [7]:
#Compute Gradient
y.backward()

In [8]:
# Print out the gradients
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [10]:
# Create a tensor of shape (10,3) and (10,2)
x = torch.randn(10,3)
y = torch.randn(10,2)

In [11]:
x

tensor([[-0.0933, -0.3684, -0.5267],
        [ 0.4480, -1.4949,  0.3124],
        [-0.4103,  0.2855, -1.2874],
        [-0.3632,  0.3125, -0.9794],
        [ 1.9856, -0.8502, -0.4797],
        [-0.1808, -0.4359, -0.2335],
        [ 1.0611,  0.3891, -0.2634],
        [-0.8529,  0.1835, -1.2900],
        [ 0.3057,  0.3376, -0.6677],
        [ 2.8572, -0.3906,  1.5938]])

In [12]:
y

tensor([[ 0.4744,  0.7479],
        [ 1.8252, -0.0585],
        [-1.1342,  1.0072],
        [ 1.0888, -1.2331],
        [-1.0294,  1.5570],
        [ 0.2660, -0.2905],
        [ 0.8143, -0.0652],
        [ 2.1063,  0.1571],
        [ 2.0930,  0.4943],
        [ 0.9028,  0.4970]])

In [14]:
# Build a fully connected layer
linear = nn.Linear(3,2)
print('w:', linear.weight)
print('b:', linear.bias)

w: Parameter containing:
tensor([[-0.5613,  0.2244, -0.4568],
        [-0.4456,  0.4453,  0.5101]], requires_grad=True)
b: Parameter containing:
tensor([ 0.1658, -0.1350], requires_grad=True)


In [15]:
# Build the loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(),lr=0.01)

In [16]:
# Foward pass
pred = linear(x)

In [17]:
# Compute loss 
loss = criterion(pred,y)

In [18]:
# Print out the gradient
print('dl/dw: ', linear.weight.grad)
print('dl/db: ', linear.bias.grad)

dl/dw:  None
dl/db:  None


In [19]:
# 1-step gradient descent
optimizer.step()

In [20]:
pred = linear(x)
loss = criterion(pred,y)
print('Loss after 1 step optimization', loss.item())

Loss after 1 step optimization 2.186506509780884


In [22]:
# Create a numpy array
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [23]:
# Convert the numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [24]:
# Convert the torch tensor to a numpy array
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [27]:
# Download and construct CIFAR-10 datasets
train_dataset = torchvision.datasets.CIFAR10(root ='./data',
train=True,transform=transforms.ToTensor(),download=True)

100%|████████████████████████| 170498071/170498071 [00:22<00:00, 7498110.10it/s]


Extracting ./data/cifar-10-python.tar.gz to ./data


In [29]:
# Fetch on dataset pair
image,label = train_dataset[0]
print(image.size())
print(label)

torch.Size([3, 32, 32])
6


In [30]:
# Data Loader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,batch_size=24,shuffle=True)

In [33]:
# When iteration starts, queue and thread start to load data from files
data_iter = iter(train_loader)

In [35]:
# Mini-batch images and labels
images,label = next(iter(data_iter))

In [36]:
images[0]
label[0]

tensor(6)